[tool.poetry]
name = "eiffel"
version = "0.1.0"
description = "Evaluation Framework for FL-based intrusion detection using Flower."
authors = ["phdcybersec <82591009+phdcybersec@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
isort = "^5.12.0"
autoflake = "^2.1.1"
tensorflow = { version = "~2.10.0", markers = "sys_platform != 'darwin'" }

[tool.poetry.scripts]
# eiffel = "eiffel:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
